### ISSUE TITLE
Lings can transform sting people into monkies

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2809] opened 2016-08-26 18:26 UTC
jesus fucking christ fix this

being turned into a monkey freezes you so they can just stun you as soon as you're out of it. It removes all of your fucking equipment, and ------MAKES YOU VALID TO THE WHOLE CREW AT THE CLICK OF A LING'S BUTTON--------, makes you unable to use machines, unable to EVEN USE GUNS

and it's PERMANENT

This is basically giving lings access to the wizard's Cluwne spell because monkeys are just as fucked as them.

**Comment by Kierany9** [comment] 2016-08-26 18:27
feature

quality feature at that

you can also turn people into hulks, or make everybody blind, deaf and spastic

**Comment by Spacedong** [comment] 2016-08-26 18:38
it instantly works and you can instantly kill the monkey by KO'ing it, go fuck yourself kierany

**Comment by tabsiforu** [comment] 2016-08-26 18:41
what's the fuck tag for?

**Comment by blobbernaut** [comment] 2016-08-26 18:47
if you think this is an okay feature and not an incredibly disgusting bug that should be permanently removed from the game you are actually a fucking moron

**Comment by Mithrandalf** [comment] 2016-08-26 18:49
It's not a bug, but it is a Bad Feature.

Nerf the sting, make it change name and appearance only.

Ree.

**Comment by Spacedong** [comment] 2016-08-26 18:50
remove newling

**Comment by Mithrandalf** [comment] 2016-08-26 18:53
remove spacedong

**Comment by GeneralGoose** [comment] 2016-08-27 07:36
lol this is cancer 
lings are cancer
not like they gonna go around stinging people, they will instead just wank to monkeys and recall shuttle for 2 hours because thats fun

**Comment by banthebantz** [comment] 2016-08-27 10:21
Why is this FUCK worthy when you can turn people into catbeasts with every single disability?

**Comment by Limed00d** [comment] 2016-08-27 10:27
not a fan of this, catbeast stings were already awful to deal with

**Comment by Alphora** [comment] 2016-08-30 03:44
Have submitted a PR addressing this #2833

**Comment by Alphora** [comment] 2016-08-31 16:34
Resolved with the merging of #2833 issue can now be closed.

**Closed** 2016-08-31 16:35 UTC
Labels: Bad Feature, Balancing, Feature
