### ISSUE TITLE
Engieborgs can only pick up red wire.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1879] opened 2016-02-15 20:36 UTC
Trying to pick up any other color wire with your wire stack tool does nothing. It can only be refilled with red wire. What the fuck?

**Comment by McBawbaggings** [comment] 2016-02-15 20:38
Can confirm. Red coils worked and the blue one didn't.

**Comment by JustinBNewton** [comment] 2016-02-15 21:40
Same with any other color of wire. Not a bug.

**Comment by Spacedong** [comment] 2016-02-15 21:42
what? what are you talking about, this is a bug, you can pick up other wire colors as human, but not a borg.

**Comment by JustinBNewton** [comment] 2016-02-15 21:42
Two ways to fix this if you really wanted to, 
1. Add every color of wire to the borg.
2. Make a wire that is able to switch colors.

**Comment by Spacedong** [comment] 2016-02-15 21:43
the borg's wire CAN switch color you dumbo

**Comment by Spacedong** [comment] 2016-02-15 21:43
STILL doesn't work

**Comment by JustinBNewton** [comment] 2016-02-15 21:44
Then switching wire color as a borg doesn't work?

**Comment by JustinBNewton** [comment] 2016-02-15 21:45
If you click any other color of wire with a red wire, it just makes it all become red. Thats a feature.

**Comment by Spacedong** [comment] 2016-02-15 21:50
I think you're missing the point here, you can't pick up any other wire color on the ground as a borg except red.

**Comment by JustinBNewton** [comment] 2016-02-15 21:50
Ah gotcha, thanks for clarifying.

**Comment by Grufus2** [comment] 2016-02-18 11:25
One solution I could see is to add something like this:

```
cable.dm:line 493

/obj/item/stack/cable_coil/attackby(obj/item/W, mob/user, params)
	..()
	if(istype(W,/obj/item/stack/cable_coil/cyborg))
		var/obj/item/stack/S = W
		merge(S)
		user << "<span class='notice'>Your [S.name] stack now contains [S.get_amount()] [S.singular_name]\s.</span>"
```

**Comment by Pyko1** [comment] 2016-02-18 11:31
might actually look in to this and slap it on my noose & gravity PR since i'm working on the file anyways,

**Comment by Pyko1** [comment] 2016-02-24 16:28
It seems engi borgs dont exactly use amount on coils, instead they have their own var for cable synthetiser, which seems to be only able to convert the red cable that is parent of all coils (colored and random). Also while snooping around I noticed it had recharge value but it does not seem to recharge at all on its own. Was not actually able to find the code that takes care of converting cable amount in to cable synth charge.

**Comment by McBawbaggings** [comment] 2016-02-24 16:59
Engiborg's cable synth is only recharged in cyborg docks
I think it's this proc that handles the recharging of modules like the cable coil:
https://github.com/HippieStationCode/HippieStation13/blob/7e8e4e70be2bf67c1be5800ef7fd0f66ff50efd6/code/game/machinery/rechargestation.dm#L139

**Comment by McBawbaggings** [comment] 2016-02-24 17:01
I think clicking on coils recharge is handled here though:
https://github.com/HippieStationCode/HippieStation13/blob/b42778a847e67335c659bdbde5308c59615fead4/code/modules/mob/living/silicon/robot/robot_modules.dm#L65

**Comment by Grufus2** [comment] 2016-02-24 17:08
Then the bug is the engieborg being able to pickup wires?

**Comment by Spacedong** [comment] 2016-02-24 20:09
the engieborg is supposed to be able to pickup wires though I thought

**Comment by Pyko1** [comment] 2016-02-24 20:25
To me it seems they are supposed to be as able to pick up wires as they are able to pick up metal/glass.

**Comment by Spacedong** [comment] 2016-02-25 22:00
engiborgs should be able to pickup any color of wire because the wait time to regenerate it when in a charging dock is looooooooooong

**Comment by JohnGinnane** [comment] 2016-03-23 13:55
I did a little testing and it seems cyborgs can pick up cables of other colours, but only if that cable has been placed and then cut. When this happens it changes its type from `/obj/item/stack/cable_coil/random` to `/obj/item/stack/cable_coil` which is something the cyborg can pick up.

For where it's handling picking up cables see https://github.com/HippieStationCode/HippieStation13/blob/2a8bfff386ddbcfd0554e35f947447053132fd2a/code/game/objects/items/stacks/stack.dm#L239

I'll do some playing around to see if I can get it consider all types of `/obj/item/stack/cable_coil` to be the same (e.g. cyborg, random, etc.)

**Comment by JohnGinnane** [comment] 2016-03-23 15:17
See https://github.com/HippieStationCode/HippieStation13/pull/2047 for the fix

**Comment by JohnGinnane** [comment] 2016-03-26 15:23
This can be closed since the fix was merged

**Closed** 2016-03-26 16:22 UTC
Labels: Bug, Confirmed
