### ISSUE TITLE
ID card sprite glitched up (not sure how to reproduce)

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1361] opened 2015-12-04 22:58 UTC
so this "thing" or something or whatever it is looks like a gumball ,but its actually my ID 

http://vgy.me/aeISRY.png

**Comment by TDcoolguy300** [comment] 2015-12-04 23:17
Glorious, no idea how your ID card somehow changed it's default icons file without admin intervention to a bloody rainbow slime extract

**Comment by Spacedong** [comment] 2015-12-05 00:34
top kek

**Comment by TDcoolguy300** [comment] 2015-12-05 15:50
With this being unable to reproduce, i am going to close it.

**Closed by TDcoolguy300** 2015-12-05 15:50 UTC
