### ISSUE TITLE
Brain rot

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1915] opened 2016-02-22 21:45 UTC
It keeps making braindamage even after cured?

**Comment by Pyko1** [comment] 2016-02-22 21:48
Confirmed by admin, braindamage keeps ticking even when the brain rot is cured from me.

**Comment by McBawbaggings** [comment] 2016-02-22 21:54
Ling panacea wasn't curing disease either properly it seems.

**Comment by Pyko1** [comment] 2016-02-22 21:57
seems like datum/disease/brainrot/stage_act() does not properly stop even if its cured.

**Comment by Kokojos** [comment] 2016-02-28 06:47
Unable to reproduce at all. Gave it to myself three times, cured it three times with manitol, and it fixed it the three times, braindamage in full.

Closing

**Closed by Kokojos** 2016-02-28 06:47 UTC
Labels: Bug, FUCK, Priority

**Comment by Pyko1** [comment] 2016-02-28 07:52
was that normal brain rot or advanced disease?

If I recall correctly we had normal brain rot going, and some advanced disease as well.
