### ISSUE TITLE
Makeshift armor takes 6 duct tape to craft.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2040] opened 2016-03-22 21:27 UTC
Yet duct tape only spawn in 5 stacks and are incredibly rare. The fuck? am I missing something here?
pls no bully

**Comment by JohnGinnane** [comment] 2016-03-22 22:09
I made changes to the makeshift armour and knife-gloves, but then I noticed my duct tape have 15 in the stack, and upon looking at https://github.com/HippieStationCode/HippieStation13/blob/43e726f168222d20f010cf18279c6be9ac4575ef/code/modules/ducttape/ducttape.dm I can see it spawns with that much. Where are you seeing 5 only?

**Comment by EMT321** [comment] 2016-03-22 22:17
I too have only found 5 stack iterations of duct tape in maintenance. I assumed it was meant to be that way.

**Comment by JohnGinnane** [comment] 2016-03-22 22:17
In that case I'll do a pull request anyway

**Comment by JohnGinnane** [comment] 2016-03-22 22:20
Ah ha, lines 189 and 190:

https://github.com/HippieStationCode/HippieStation13/blob/f6c66f301d8eb01c060e7d8a4ff49e7caf4ff039/code/game/objects/effects/spawners/lootdrop.dm

**Comment by JohnGinnane** [comment] 2016-03-22 22:51
See: https://github.com/HippieStationCode/HippieStation13/pull/2043

**Comment by Pyko1** [comment] 2016-03-23 15:54
Wrong lines actually, those are for contraband. But its more or less the same for the maintloot anyways.

**Comment by Pyko1** [comment] 2016-03-24 15:47
not a bug, closing

**Closed by Pyko1** 2016-03-24 15:47 UTC
Labels: Balancing
