### ISSUE TITLE
Cloaks are fucked

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2835] opened 2016-08-30 15:05 UTC
You can't change how you wear them(as a backpack or as armour, it gives the message "You can't adjust the cloak while it has items inside." even if it's completely empty.

Their inhand sprites are backpacks

The CMO's cloak(and possibly others) is somehow breaking the steal disk objective for KotD and I have no idea how or why.

**Comment by ArcLumin** [comment] 2016-08-30 15:12
Wait, didn't I make an issue about this before? Or did I forget to.

**Comment by ArcLumin** [comment] 2016-08-30 15:13
Oh wait I did. https://github.com/HippieStationCode/HippieStation13/issues/2789

**Comment by tabsiforu** [comment] 2016-08-30 17:00
Cloaks are pretty fucking useless anyway, seeing as there's already armour that does their job better for every class which has them.

**Comment by Mithrandalf** [comment] 2016-08-30 17:02
psure armour stacks now, so a cloak on your back plus your relevant armour will result in even MORE armour.

**Comment by tabsiforu** [comment] 2016-08-30 17:06
Doesn't the cloak go where the armour is supposed to? If that is true, then why wear the cloak?

**Comment by Mithrandalf** [comment] 2016-08-30 17:06
It can go in either exosuit or backpack last I checked. I dont use it much.

I know 100% that it works in backpack slot.

**Comment by tabsiforu** [comment] 2016-08-30 17:08
There would need to be a lot of incentive for somebody to give up their forever-useful backpack (sacrifice one slot to hold ten more items) just for some armour. It seems very niche to me.

**Comment by Mithrandalf** [comment] 2016-08-30 17:09
The cloak stores items as well, you know.

**Comment by tabsiforu** [comment] 2016-08-30 17:13
In this scenario it is helpful to describe how many items and what type of items they can hold. I don't know. If I did I would contribute smarter.

In addition, the Wiki says that two cloaks are garbage, two are situational, and one is an upgrade. I'm wondering what the purpose of these cloaks are then. http://wiki.hippiestation.com/index.php?title=Guide_to_Combat#Cloaks

**Comment by Mithrandalf** [comment] 2016-08-30 17:17
The wiki is woefully out of date because our resident gay furry abandoned us for his dragon waifu.

As far as I'm aware, cloaks are a tradeoff. Slightly less capacity for storage in return for additional armour.

**Comment by tabsiforu** [comment] 2016-08-30 17:20
I believe there are a few problems with cloaks:

*they are poorly advertised as being equippable in the backpack slot
*the backpack holds far more than a cloak can, making it less practical and more easily ignored
*the armour gain is not compelling enough to abandon the ever-useful backpack

It seems its niche is a fast type of armour that can be easily stolen (but can't be right now because it's stuck in the Heads lockers) and has special benefits unique to each one, but right now it isn't capitalising on these benefits to be compelling enough to the majority of players.

**Comment by Mithrandalf** [comment] 2016-08-30 17:22
No. It's a trade-off you can choose to make as a head if the situation arises. Just because you wouldn't use them doesn't mean there's an issue at all. I've just been humouring you because you seemed confused about the specific mechanics.

The issue here is with the code. They're causing problems as listed in kierany's post.

Why are you trying to derail this into a completely different subject?

**Comment by tabsiforu** [comment] 2016-08-30 17:33
Because it's convenient.

I think the problem is that, from a game theory perspective, this game prioritises having a big inventory space to hold a lot of useful items in. Nothing wrong with that - it's just how the game works. The issue is when it's in relation to deciding whether or not to give up this big priority, this ability to have a shit-ton of items, in favour of having a little more armour.

And a reasonable player who understands this meta would find that the cloak is inferior to the backpack in this respect, unless there was some other mechanic so compelling that they would want to give up the inventory space.

**Comment by Kierany9** [comment] 2016-08-30 17:47
Yo can you not shitpost like you own the repo k thanks. This is about cloaks having an assortment of bugs and glitches that need to be adressed, not about balancing.

**Comment by ArcLumin** [comment] 2016-08-30 20:12
Look at the code: Cloaks actually can give lots of fairly good defense that stacks on top of normal armor. Plus, the actual loss in storage space is only two large items, rectified by using other methods of storage space. It's still a trade off, but it works well for additional defenses (which stack with your other armors).

Plus they're swanky as fuck.

Anyways, back to the topic at hand, inhand sprites aren't a huge issue; many things have some inhand sprite differences, and this one isn't too bad. 

As for the cloak mode alteration, that's been broken since it was implemented, sadly. Likely an issue with checking the items. Prolly a better idea for it to forcibly drop all items (or most if you want to to still have some space on the armor slot) and then equip, rather than returning if it thinks something is in it

**Comment by blobbernaut** [comment] 2016-08-30 20:24
I'll take a look when I'm home

**Comment by blobbernaut** [comment] 2016-08-30 20:28
Also keep in mind 99% of people aim head anyway

**Comment by ArcLumin** [comment] 2016-09-12 17:16
This has been fixed by https://github.com/HippieStationCode/HippieStation13/pull/2860

**Closed** 2016-09-12 17:18 UTC
