### ISSUE TITLE
syndicate shuttle walls are deconstructable

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#1837] opened 2016-02-08 00:25 UTC
apply welder to syndicate shuttle

congratulations it's easier to get into than the armory, captain's office, etc.

**Comment by Nokington** [comment] 2016-02-08 00:30
This should be fixed imo because its pretty shit to have your nuke stolen the moment you hit the station.

**Comment by ArcLumin** [comment] 2016-02-08 06:08
Or, you can have a nuke op protect the nuke. Or not put the ship in such an obvious location as below the singulo or above the armory

Still, it's a balancing issue. Putting one nuke op on guard duty does lower the effectiveness of the team as a whole. But the best way to counteract this? Just bring the nuke with you. OR put it's bolts down, it has bolts, in case you didn't know.

**Comment by Pyko1** [comment] 2016-02-08 09:22
Or you can pull the tile in to shuttle bridge where its in between of 4 turrets.

**Comment by JustinBNewton** [comment] 2016-02-08 10:08
Its already up in the shuttle bridge as of a few hours ago. At least I think it is at round start...

Regardless, thats a quick fix..

**Comment by Nebyab** [comment] 2016-02-11 20:57
dumb and stupid

walls used to be indestructible for a reason
though not a bug

**Comment by JustinBNewton** [comment] 2016-02-11 21:56
not a bug according to heads

**Closed by JustinBNewton** 2016-02-11 21:56 UTC
Labels: Balancing, FUCK, Needs Head Input
