### ISSUE TITLE
Upgrading the microwaves/gibber no longer increases the amount of food you receive.

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2189] opened 2016-04-20 19:46 UTC
pls fix i want to make the super big bite burgers

**Comment by carlarc** [comment] 2016-04-20 21:38
Gimme a burg

**Comment by ArcLumin** [comment] 2016-06-07 15:49
Wasn't this removed from /tg/ code years ago because people were cloning donk pockets and letting them cool, then re microwaving them, then grinding them down for infinite tricord?

**Comment by 2Dollarbill** [comment] 2016-06-07 20:10
I mean you can technically make infinite Omnizine using botany, while this requires science research and someone actually bothering to upgrade your microwaves. I'm fine with putting it back.

**Comment by Gandalf2k15** [comment] 2016-06-07 20:57
I'll get putting this back then

**Comment by Spacedong** [comment] 2016-07-10 21:23
this isn't a bug its from shitty tablecrafting, close this

**Comment by Gandalf2k15** [comment] 2016-07-10 21:23
Not a bug, bad feature.

**Closed by Gandalf2k15** 2016-07-10 21:23 UTC
