### ISSUE TITLE
The pickaxes on the off-station permabrig aren't safety pickaxes

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2486] opened 2016-06-05 23:34 UTC
good work they do a full whoppin 15 damage @calibraptor

**Comment by calibraptor** [comment] 2016-06-06 01:07
It's intended.

**Comment by trifornt-tinfornt** [comment] 2016-06-06 06:16
That's stupid though. Safety Pickaxes are just as good at mining as the rest.

**Comment by calibraptor** [comment] 2016-06-06 07:02
They're not very good at fighting off mining critters though.

**Comment by danhibiki** [comment] 2016-06-06 07:16
Prisoners are suppose to be protected from assailants by their captors (sec isn't suppose to let prisoners die 4noraisin). The burden of fighting the critters falls on sec, not the prisoners.

**Comment by TheOneAndOnlyCreeperJoe** [comment] 2016-06-06 08:01
@danhibiki Stop right there that instant; you shouldn't balance things around 'how it should be', because in practice that is almost never the case. Security will just throw prisoners into Perma and leave it at that, they won't stick around to watch them they'll just be left. We're a gameplay server not a roleplay server, sec's gonna do whatever the fuck it wants and you cannot obligate them to babysit the permabrig. Keep it as is, being unable to reliably fight asteroid mobs is a real pain and despite most of them being avoidable, it is still a necessity for them to have a means of dealing it on their own.

**Comment by danhibiki** [comment] 2016-06-06 08:05
That would be a dandy argument if you weren't arguing for giving miners a 15 brute weapon.

**Comment by TheOneAndOnlyCreeperJoe** [comment] 2016-06-06 08:15
The thing is; usually at fault of the terrain generation the whole Permabrig mining area will be surrounded by a cave (this is also caused by the xeno outpost which will always have at least 1 cave connected to it), meaning that unless you tediously grind every single piece of iron ore in that small secluded area. It can even get worse at times where the cave is literally hugging the edge of it.

It's a requirement for anyone that goes mining on the leftside to have a means of fighting off the wildlife. If terrain generation is shit then it sometimes may not even happen that you can physically mine enough ores before being hentai'd by a Goliath. They need a starting weapon, point. Even if melee-ing a Goliath is the worst thing you could ever do, it is needed (and it's possible to kill goliaths in melee without a scratch). But not the Kinetic accelerator, their tunneling capabilities equal that of a diamond drill and allows for some very quick escapes. They should earn their escape not be given it from the getgo.

Not to mention that the prisoners can get even better weapons anyway if they got lucky and have an artifact room spawn close-by.

**Comment by danhibiki** [comment] 2016-06-06 09:15
There is a huge problem with giving prisoners an instantly acquirable 15 brute weapon when we already have a pickaxe coded for just this very situation.

**Comment by TheOneAndOnlyCreeperJoe** [comment] 2016-06-06 09:26
The point overshoots your head; they need a good weapon point, or they're dead to mining mobs. Security isn't going to swoop by to help them, there isn't a compromise. Either they get shit weapons and are basically marked for death when they encounter a mob due to terrain generation or they start with a pickaxe with high brute that may be used to beat people up but in term actually gives them a chance of living trough the asteroid.

**Comment by danhibiki** [comment] 2016-06-06 10:00
Perhaps the intent of a perma situation over shoots your head. Anyone tossed to perma has done some serious shit. You want them to have some passage to freedom, and a chance to explore. Mining doesn't need to be a safe option if it also gives them incredibly powerful weapons.

**Comment by TheOneAndOnlyCreeperJoe** [comment] 2016-06-06 10:02
Giving them the shitty plastic pickaxe is basically leaving them for death at the hands of the asteroid mobs due to the terrain generation mentioned earlier, the only thing they could defeat with it is a hivelord or goldgrub, but the moment a Basilisk or Goliath swings around they're 100% dead.

**Comment by doobiedoo23** [comment] 2016-06-06 10:05
if you're bad enough at sec to get killed by a prisoner with a pickaxe you deserve it, keep them in

**Comment by Mithrandalf** [comment] 2016-06-06 11:01
Bucket of water from botany + pickaxe = dead security.

Make the mining section a safe zone and an air pocket like with the old gulag. Remove the air tanks. Replace the picks with safety picks.

As it is, there are a million zero-risk escape routes. Perma isnt worth using at all.

**Comment by Gandalf2k15** [comment] 2016-06-06 14:01
this was fixed I think too

**Comment by Gandalf2k15** [comment] 2016-06-06 15:09
Fixed in https://github.com/HippieStationCode/HippieStation13/pull/2488

**Comment by calibraptor** [comment] 2016-06-06 19:33
@Gandalf2k15 This is honestly a non-issue. The real pickaxes being there are intended so prisoners can fight off mining mobs.

**Closed** 2016-06-09 23:39 UTC
