### ISSUE TITLE
White ship doesn't line up with Derelict

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#2017] opened 2016-03-17 19:43 UTC
https://vgy.me/xe6MdZ.png

aaaaa

**Comment by EMT321** [comment] 2016-03-17 21:47
It's been that way forever, I just break the glass or walk around the ship.

**Comment by Pyko1** [comment] 2016-03-18 21:39
duplicate of https://github.com/HippieStationCode/HippieStation13/issues/1553

**Closed by Pyko1** 2016-03-18 21:39 UTC
Labels: Bug, Confirmed, Mapping
