### ISSUE TITLE
Prison Monitor in HOP Office doesn't have any cameras to jump to.

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1590] opened 2016-01-03 02:07 UTC
http://vgy.me/LM0ZeO.png

**Comment by XeonFaux** [comment] 2016-01-03 11:10
Just tested this, works perfectly. Not a issue.

**Comment by danhibiki** [comment] 2016-01-03 11:13
Well, that really asks how this specific bug happened then for sure.

**Comment by XeonFaux** [comment] 2016-01-03 11:19
Possibly camera's were disabled? Or EMP'd?

**Comment by Kokojos** [comment] 2016-01-03 23:59
Unable to reproduce, closing.

**Closed by Kokojos** 2016-01-03 23:59 UTC
Labels: Can Not Reproduce, Mapping
