### ISSUE TITLE
Syndicate bomb cores

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2258] opened 2016-05-02 14:19 UTC
Dont seem to get triggered by nuke op bomb implants.

**Comment by Spacedong** [comment] 2016-05-13 22:22
this is so vague why please close this unless you give more information

**Comment by Pyko1** [comment] 2016-05-16 12:46
If you carry a syndicate bomb core, and you detonate your explosive implant, it does not trigger the said bomb core. 
Even tho the bomb cores should be triggered by explosions and from being set on fire.

**Comment by Pyko1** [comment] 2016-05-16 12:47
Havent checked, but i assume that there is some kind of code in explosive implants that ensure your gear gets destroyed before the actual explosion happens.

**Comment by Pyko1** [comment] 2016-05-16 13:03
looks like it works, now, but i have had it fail to some unknown reason. ill try to investigate more.

**Comment by Pyko1** [comment] 2016-05-16 13:14
After doing some more testing. Explosive implant wont trigger bomb cores you carry or have implanted on you, if you are laying down for some reason.

**Comment by Spacedong** [comment] 2016-07-14 18:13
close this, its not a bug

**Comment by Spacedong** [comment] 2016-07-15 01:52
not a bug, close

**Closed** 2016-07-15 03:06 UTC
