### ISSUE TITLE
Embedding caused by explosions can not be pulled out at all. (JESUS FUCK) 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1138] opened 2015-11-05 02:48 UTC
Apparently its only because of explosions embedding shit in people, you can't take it out and it remains inside you until you die. Horribe horrible bug and its the death of medbay staff everywhere.

**Comment by Chronitonity** [comment] 2015-11-05 02:48
Dupe of #1108 Post results and jazz there.

**Closed by Chronitonity** 2015-11-05 02:48 UTC
