### ISSUE TITLE
power fist costs half your TC but you can be easily instantly disarmed of it and killed with it 

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#3312] opened 2017-01-07 23:24 UTC
crawling in my skin, these wounds, they will, not heal

**Comment by MethMedic** [comment] 2017-01-07 23:25
Make it so you wear it as a glove

**Comment by KittyKathy** [comment] 2017-01-08 00:55
Meth actually has a good idea it should be worn as gloves and it gives a action button like defibrillators that activates the gloves and puts the item into your hand so you can use it, making it a bit more stealthy and you can't be disarmed and killed with it.
It would work the same way defibrillators and paddles work, when you have it activated and get stunned it should just deactivate it, maybe getting disarmed should deactivate it too or not.
Maybe it could also be wielded with two hands for a special punch that sends them flying back and does more damage depending on how far they fly. Or the two handed mode can be used for a special attack that pounds the floor damaging it and sending people back like the Sorium reagent or wizard repulse spell. (Ground Pound for the attack name?)
These special attacks should have a cool down though so they can't be spammed.
We need better melee everyone is just like grab a gun it is always better.

**Comment by ArcLumin** [comment] 2017-01-08 01:35
We actually had something like that in the code, but it was a stun and not a weapon.

I agree for a push for better melee, and I agree it's stupid as shit that it's that expensive. I intend to do a full tc prices rework in the future

**Comment by Spacedong** [comment] 2017-01-08 05:01
S T U N  G L O V E S

**Comment by MethMedic** [comment] 2017-01-08 05:25
Honestly we need an uplink rework. Some items are basically useless

**Comment by ArcLumin** [comment] 2017-01-08 05:26
yeah. I intend to significantly lower the more worthless one as a small adjustment, but a lot of them need to be buffed in general

**Comment by MethMedic** [comment] 2017-01-08 05:28
Chameleon stamp is one example of something that I've only ever heard of it being used once

**Comment by Dudeinyourbackyard** [comment] 2017-01-08 05:31
make it a suggestion, this isn't an actual bug/issue

**Comment by Spacedong** [comment] 2017-01-08 05:49
you're not an actual bug/issue bruce, but im still gonna remove yuo anyway

**Comment by Dudeinyourbackyard** [comment] 2017-01-08 05:51
please do

**Comment by TDcoolguy300** [comment] 2017-01-08 06:00
Not a bug, closing

**Closed by TDcoolguy300** 2017-01-08 06:00 UTC
