### ISSUE TITLE
Morphine allows you to crawl at top speed

### ISSUE THREAD

**Issue by Kierany9** [HippieStationCode/HippieStation13#2579] opened 2016-06-29 16:52 UTC
This, while absolutely hilarious, will either almost instantly send you into deep crit or let you crawl like sanic depending on whether you have epinephrine in you or not.

Also to save whoever fixes this some time, the issue seems to be [here in the movement proc](https://github.com/HippieStationCode/HippieStation13/blob/b149a510ae9aa5a2ea4339f59c14b69b42794bdb/code/modules/mob/living/carbon/human/species.dm#L917), where the ignoreslowdown flag is checked before applying any slowdown, regardless of slowdowns that should not be ignorable such as missing legs or being in critical condition.

**Comment by JohnGinnane** [comment] 2016-06-29 17:31
This issue was raised before and we decided to leave it in because it was/is hilarious: https://github.com/HippieStationCode/HippieStation13/issues/2114

If you want people to crawl to their death at supersonic speeds let them

**Comment by danhibiki** [comment] 2016-07-01 08:51
Its funny because you commented on this issue last time and said it was OK to keep.

**Comment by blobbernaut** [comment] 2016-07-01 12:26
classic case of a bug becoming a feature

**Comment by blobbernaut** [comment] 2016-07-01 12:27
since this IS a bug though, a comment in the code to document it as intended behavior would do

**Comment by McBawbaggings** [comment] 2016-07-01 12:33
>Take meth
Take Dexalin
Ask someone to crit you with a lit welder

**Comment by blobbernaut** [comment] 2016-07-01 12:33
dexalin a thing??

**Comment by GeneralGoose** [comment] 2016-07-02 22:08
its not a bug or a feature
its a meme

**Comment by Spacedong** [comment] 2016-07-09 00:28
close this, non-issue, we agreed it was okay to keep in the game because its hilarious and doesn't happen often

**Closed** 2016-07-09 00:29 UTC
Labels: Bug, Feature, Working as Intended
