### ISSUE TITLE
Canvas are broken

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1320] opened 2015-11-29 00:22 UTC
Turn invisible when clicked on, when you try to draw on them you start drawing a letter on the floor under them, buggy piece of shit etc.

**Comment by Spacedong** [comment] 2015-11-29 00:23
also you cant even draw anything or drag your mouse to draw, tbh it should work like a paper where you shift click it THEN start drawing on it i.e. microsoft paint like html papers ag

**Comment by Crystalwarrior** [comment] 2015-12-14 10:23
port my Atlas canvases already JEZZZZ
Atlas-Station canvases are an expanded and fixed up version of /tg/ canvases

**Comment by Crystalwarrior** [comment] 2015-12-14 10:27
this issue is duplicate of https://github.com/HippieStationCode/HippieStation13/issues/1239

**Closed by Crystalwarrior** 2015-12-14 10:27 UTC
Labels: Bug, Coding, Duplicate
