### ISSUE TITLE
Smoking ambrosia vulgaris yields no space drugs effect, regardless of potency

### ISSUE THREAD

**Issue by Spacedong** [HippieStationCode/HippieStation13#1592] opened 2016-01-03 05:07 UTC
haven't tested ambrosia deus yet but I'm sure the ambrosia vulgaris thing is bugged

**Comment by McHatters** [comment] 2016-01-03 23:46
I don't remember the details but I think it has something to do with the biggest reagent in a mixture being metabolized while smoking. When you roll up ambrosia vulgaris, the amount of drugs in the mixture is equal to some other reagent inside it (like nutriment or something). As a result, you don't metabolize the drugs.

**Comment by danhibiki** [comment] 2016-01-03 23:50
This just isn't true, unless your smoking some really weak ambrosia. The problem is the amount of chems it has of everything else, and when I increased spacedrugs, everyone was "zomg increeze omnizine". I know, in testing, 50 potency ambrosia vulgaris yields space drug effect, and I can even test this live.

**Comment by TDcoolguy300** [comment] 2016-01-05 05:37
Assuming this is a non-issue, i'll go ahead and close it

**Closed by TDcoolguy300** 2016-01-05 05:37 UTC
