### ISSUE TITLE
Meatspikes

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#2256] opened 2016-05-02 13:37 UTC
Seem to be broken, they dont kill punpun and even if you kill it you cant remove meat.

**Comment by Spacedong** [comment] 2016-05-13 00:30
close this you retard its been like this ever since rebase, its a feature, not a bug, they only killed monkies instantly in pre-rebase, how many non-issues will you make jesus christ afhndjksgfxvbncjcxvb

**Closed** 2016-05-13 00:37 UTC
Labels: Bug
