### ISSUE TITLE
HONK mech starts with an access restriction

### ISSUE THREAD

**Issue by blobbernaut** [HippieStationCode/HippieStation13#2434] opened 2016-05-25 19:52 UTC
why?

if you build it you should get it

**Comment by carlarc** [comment] 2016-05-26 04:12
odysseus too

**Comment by carlarc** [comment] 2016-05-26 04:12
fun fact: mime can get in honkmech too since he has theatre access

**Comment by Carbonhell** [comment] 2016-05-28 13:05
only clowns should drive honk mechs tbh,and it's not a bug but a feature so it shouldn't even be here but rather on the forum,closing

**Closed by Carbonhell** 2016-05-28 13:05 UTC
