### ISSUE TITLE
Dream Seeker Crash

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#1031] opened 2015-10-25 14:56 UTC
![capture](https://cloud.githubusercontent.com/assets/12048747/10716194/5595a25e-7b39-11e5-8331-6170d11809d9.PNG)
Examined the deepfried clown twice, crashed both times.

**Comment by Carbonhell** [comment] 2015-10-25 14:57
You sure it was caused by that?I get random crashes sometimes too

**Comment by Pyko1** [comment] 2015-10-25 14:58
happened twice, when i examined the clown

**Comment by Carbonhell** [comment] 2015-10-25 18:08
Asked other people the round immediately after and noone noticed this bug even after examining this guy. I'll try to reproduce it tomorrow.

**Comment by Carbonhell** [comment] 2015-10-26 19:11
Close this,the issue made now is more detailed

**Closed** 2015-10-29 03:43 UTC
