### ISSUE TITLE
Closing PDA from last round

### ISSUE THREAD

**Issue by Pyko1** [HippieStationCode/HippieStation13#563] opened 2015-09-11 16:30 UTC
You have to wait for the next round to start and open your new PDA before you can close the PDA window from last round.

**Comment by JustinBNewton** [comment] 2015-09-13 09:55
Can be fixed by allowing window close in game (ie system based closing) needs testing.

**Comment by Chnkr** [comment] 2015-09-14 17:08
Not a bug.

**Comment by Chronitonity** [comment] 2015-09-14 17:09
Unless you have something helpful to comment then you probably shouldn't be commenting amigo.

**Closed** 2015-09-19 18:07 UTC
